### ISSUE TITLE
천공의 노래의 데미지%가 코강 타겟수+1을 받지 않습니다.

### ISSUE THREAD

**Issue by icepeng** [ParkKyuSeon/Maplestory_DPM#11]
안녕하세요. 윈브 천공의 노래 적용에 관해 질문이 있어 이슈를 남깁니다.

https://github.com/ParkKyuSeon/Maplestory_DPM/blob/a24221e06b54e4fc70c2abed635d825e8a5a5f19/WindBreaker.R#L376

`ifelse(WindBreakerCore[[1]][1, 2]>=20, 4, 3)` 부분이 코어 강화로 인한 타겟수 증가를 반영하신 것으로 생각됩니다.

최근 실험들에 따르면, 천공의 노래를 포함한 타겟수 감소당 데미지, 최종뎀 증가 효과가 코강 혹은 어빌리티의 타겟수 +1이 적용되지 않는 것으로 추정됩니다.
* https://github.com/oleneyl/maplestory_dpm_calc/issues/640
* https://github.com/Monolith11/memo/issues/117

**Comment by ParkKyuSeon** [comment]
`option <- factor(c("IGR", "BDR", "FDR"), levels=ASkill)`
`value <- c(ifelse(WindBreakerCore[[1]][1, 2]>=40, 20, 0), ((1.2 + 0.01 * floor(WindBreakerSpec$SkillLv/2))^3) * 100 - 100 + 50, 2 * WindBreakerCore[[1]][1, 2])
`


스펙 입력 부분을 수정해야 해서 아직 DPM 값에 반영하지는 않았으나 코드는 수정완료하였습니다.
감사합니다.
