### ISSUE TITLE
배틀쉽 봄버의 캡틴 디그니티 트리거 여부

### ISSUE THREAD

**Issue by icepeng** [ParkKyuSeon/Maplestory_DPM#14]
https://github.com/ParkKyuSeon/Maplestory_DPM/blob/3e322f56013b27298efbf5c817160091f5350a4e/job/Captain.R#L882

클라이언트 상에서 5221028.finalAttack에 5220020이 할당되어 있는 것으로 보아, 사인 오브 봄바드로 발생하는 폭격에도 캡틴 디그니티 추가타가 발동할 것으로 보이는데, 인게임에서 확인이 필요해 보입니다.

**Comment by icepeng** [comment]
발동 안하는 것으로 확인했습니다.

**Comment by ParkKyuSeon** [comment]
확인 감사드립니다. 말씀해주신 김에 컨티뉴얼 에이밍도 확인해봤는데 얘도 안 터지네요. 이건 터질만 한 것 같은데..
