### ISSUE TITLE
퀵 드로우 로직 문의

### ISSUE THREAD

**Issue by icepeng** [ParkKyuSeon/Maplestory_DPM#15]
https://github.com/ParkKyuSeon/Maplestory_DPM/blob/3e322f56013b27298efbf5c817160091f5350a4e/job/Captain.R#L913-L921

1) 인게임에서 확인한 결과 헤드샷으로도 퀵 드로우가 발동할 수 있습니다. 현재 코드상에서는 "퀵 드로우의 확률 스택 증가" 로직과 "퀵 드로우 버프 소모" 로직이 else-if로 묶여있는데, "HeadShot"이 두번째 분기로 진입하고 있는지 확인이 필요해 보입니다.

2) 퀵 드로우 확률을 쌓는 스킬에 캡틴 디그니티가 포함되어 있는데, 리마스터 이후 검증이 된 부분인가요?

3) QuickDrawFDR의 계산 방식이 min(퀵 드로우 스택 횟수 * 스택당 확률, 1) * (발동시 최종뎀)으로 된 것으로 보이는데, (1 - pow(1 - 스택당 확률, 스택 횟수)) * (발동시 최종뎀)이 정확할 것으로 보입니다. 9%를 12번 이상 시도했다고 해서 반드시 100%가 된다고 볼 수 없기 때문입니다.

**Comment by ParkKyuSeon** [comment]
1. 기존에는 스택 로직, 버프 로직을 따로 관리하고 있었는데 하나로 합치다 문제가 발생했네요. 다행히도 대부분의 헤샷이 퀵드 발동 상태로 들어가고 있기는 했습니다. 

2. 확인하진 않았었는데, 방금 확인해 보니 적용됩니다.

3. 이 부분도 말씀해주신 대로 수정하는 것이 정확할 것 같습니다. 다만 아마 큰 문제를 일으키고 있지는 않았을겁니다. 왜냐면 헤드 샷과 헤드 샷 사이에 래파가 36회 사용되는데, 래파 36회 + 디그니티 36회 하면 퀵드가 안 터질 확률이 0.1% 수준입니다. 따라서 헤샷 - 헤샷 사이에 데드아이가 끼어드는 경우가 아니면 거의 최대 최종 데미지로 적용이 되기는 합니다.

우선 퀵드로직은 나갔다 올 일이 있어서 들어와서 수정하겠습니다. 감사합니다.

**Comment by icepeng** [comment]
파이널 어택류 스킬이 퀵 드로우를 발동하는게 신기하네요. 답변 감사합니다.

**Comment by ParkKyuSeon** [comment]
https://github.com/ParkKyuSeon/Maplestory_DPM/blob/main/job/Captain.R#L909-L924

퀵드 로직 수정 완료했습니다. 감사합니다 :)

**Comment by icepeng** [comment]
https://github.com/ParkKyuSeon/Maplestory_DPM/blob/cdf19fc04e772eacf7111f29917a2ad01d38ae63/job/Captain.R#L917

헤드샷 이후 퀵 드로우 스택이 1이 아닌 (1-p)^s로 대입되는 이유가 어떤것인가요?

**Comment by ParkKyuSeon** [comment]
퀵드가 소모된 헤드 샷으로 인해서는 퀵드가 발생할 수 없는 것으로 알고 있습니다.
퀵드가 소모된 헤드 샷으로 퀵드가 발생한 경우는 헤드 샷에 의해 발생한 디그니티에 의해 퀵드가 발생한 경우일겁니다.

**Comment by icepeng** [comment]
디그니티는 따로 계산될테니, 헤드샷 발동시 퀵드가 적용되었는지만 영향을 끼치겠네요.

퀵드가 없을때 헤드샷을 사용한 경우 -> 스택 = 1
퀵드가 있을때 헤드샷을 사용한 경우 -> 스택 = 0

퀵드가 없었을 확률 = `(1 - QuickDrawProb) ^ DealCycle$QuickDrawStack[i-1]`
퀵드가 있었을 확률 = `1 - (1 - QuickDrawProb) ^ DealCycle$QuickDrawStack[i-1]`

따라서 `(1 - QuickDrawProb) ^ DealCycle$QuickDrawStack[i]`가 아닌 `(1 - QuickDrawProb) ^ DealCycle$QuickDrawStack[i-1]`이 옳다고 생각되는데, 확인 부탁드립니다.



퀵드가 소모된 헤드샷으로 퀵드가 발생 가능한지는 헤드샷으로 한방이 나는 사냥터에서 계속 쏴보면 검증이 가능할 것 같습니다.

몹이 한방에 죽으면 디그니티가 발동이 안되더라고요. 딜량에 영향은 거의 없을거라 생각하지만 재사용어빌을 채용할 일이 생긴다면 유의미할수도 있으니, 시간 날때 한번 확인해보겠습니다.

추가) 50번정도 해봤는데 퀵드가 켜지는 경우가 없는것으로 보아 퀵드 헤드샷으로는 퀵드가 발생하지 않는다고 보는게 맞겠네요.

**Comment by ParkKyuSeon** [comment]
실험 감사드립니다. 말씀해 주신 부분은 코드 수정 완료했습니다.
