### ISSUE TITLE
캡틴 딜사이클 주기 문의

### ISSUE THREAD

**Issue by icepeng** [ParkKyuSeon/Maplestory_DPM#16]
https://github.com/ParkKyuSeon/Maplestory_DPM/blob/3e322f56013b27298efbf5c817160091f5350a4e/job/Captain.R#L447

캡틴의 스킬들을 살펴볼 때 하이퍼 스킬의 주기가 180초보다 짧고, 5차 스킬도 모두 180초 이내의 쿨타임을 가지고 있어 1주기를 171초로 잡는것이 일반적이라고 생각합니다.

얼티밋 다크 사이트(190초)를 기준으로 하는 나이트로드의 경우 180.5초로 설정된 것으로 보아 쿨감%를 별도로 처리하는 것 같지는 않은데, 180초로 설정된 이유가 있는지 문의드립니다.

**Comment by ParkKyuSeon** [comment]
> https://github.com/ParkKyuSeon/Maplestory_DPM/blob/3e322f56013b27298efbf5c817160091f5350a4e/job/Captain.R#L459

여기서 처리하고 있습니다. 하이퍼스킬 영향 받는 직업들은 저기서 쿨감을 적용하지 않습니다.
사실 나로쪽이 예외케이스인데, 시간될때 통일하도록 하겠습니다.

**Comment by icepeng** [comment]
나로쪽만 보고 섣불리 판단해서 오해를 해버렸네요. 답변 감사합니다.
