### ISSUE TITLE
쌍권총 크루의 퍼뎀 문의

### ISSUE THREAD

**Issue by icepeng** [ParkKyuSeon/Maplestory_DPM#17]
https://github.com/ParkKyuSeon/Maplestory_DPM/blob/a1fb3c5dbdff566b328dc872a8d2d7fd8771406e/job/Captain.R#L365

서먼 크루
120초 동안 적을 150%로 3번 공격하는 탄환을 2개 발사하는 노틸러스 선원 소환

어셈블 크루
쌍권총 크루: 탄환의 데미지 200% 증가

탄환의 데미지가 200%**로** 증가가 아닌 200% 증가인 것으로 보아 150 + 200으로 적용될 것으로 보이는데, 확인 부탁드립니다.

덧붙여 150 + 200으로 적용되는게 맞다면 언위어링 넥타 쌍권총의 285%는 350%보다 낮으므로, 이 경우에도 285 + 200으로 적용되고 있을 것이라고 생각합니다.

**Comment by icepeng** [comment]
제가 측정한 캡틴 dpm의 타 직업 대비 배율이 업로드하신 자료에 비해 차이가 커서, 딜점유율을 확인하던 도중 서먼 크루의 딜 점유율 차이가 크게 나는 것을 확인하고 이슈를 작성하게 되었습니다.

**Comment by ParkKyuSeon** [comment]
확인 결과 200%p 증가로 적용되는 것이 맞네요(넥타 상태에서도 동일). 혹시나 뎀퍼 200%일지도 확인해 보았으나, 이건 아닌 것 같습니다.
반영하여 수정하였습니다. 감사합니다.

**Comment by ParkKyuSeon** [comment]
추가로, 전 직업 DPM 점유율 자료도 업데이트하였으니 참고해 보시면 좋을 듯 합니다.
