### ISSUE TITLE
불독 포이즌 체인 정의에 관한 질문

### ISSUE THREAD

**Issue by icepeng** [ParkKyuSeon/Maplestory_DPM#7]
안녕하세요. 불독 포이즌 체인 적용에 관해 질문이 있어 이슈를 남깁니다.

https://github.com/ParkKyuSeon/Maplestory_DPM/blob/15d80e750ac86cf2d0d3c1be8db072a525217b41/ArchmageFP.R#L646-L693

해당 정의를 살펴보면 `PoisonChainPre`는 중독을 일으키는 공격으로 보이고, 나머지 1~Max는 매 중독 폭발때마다 들어가는 딜을 정의하는 것으로 보입니다. 그렇게 의도하신게 맞다면, 폭발의 데미지는 `300+12*level`이 아닌 `150+6*level`로 알고 있습니다. 확인 부탁드립니다.

한가지 건의사항이 있습니다.

https://github.com/ParkKyuSeon/Maplestory_DPM/blob/93be6d54627ed8b495c5ac87458382841def35e3/JobFunctions.R#L705-L731

불독 부분의 소스코드만 보고는 포이즌 체인이 어떻게 1부터 2,3,4,5,Max까지 이어지는지 파악하기 힘들었습니다. JobFunctions의 특정 직업만을 위한 코드들을 ArchmageFP_Helper.R 과 같은 별개 파일로 분리하면 트리 뷰에서 같은 직업에 관련된 코드끼리 붙어서 나와 처음 프로젝트를 살펴볼때 접근성이 좋아질 것 같습니다.

**Comment by ParkKyuSeon** [comment]
1. PoisonChain1~Max는 폭발 데미지가 맞습니다. 해당 부분 수정하였습니다. 감사합니다.
2. 제안해주신 부분은 반영하도록 하겠습니다. 외부에 공개하려는 목적으로 짠 코드는 아니다보니 미흡한 부분이 있었습니다.  다만 지금 당장 수정할 시간이 많지는 않아 차차 수정해나가도록 하겠습니다.

**Comment by icepeng** [comment]
혹시 제가 해당 작업을 해서 Pull Request를 남겨도 괜찮을까요?

**Comment by ParkKyuSeon** [comment]
2번관련된 부분 말씀하시는건가요? 당연히 괜찮습니다. 감사합니다.
